[package]
name = "pcs"
description = "Plonk polynomial commitment scheme(KZG10)"
version = "0.1.0"
edition = "2021"
authors = ["baraka"]
license = "MIT"

[dependencies]
ark-ff = {version = "0.3.0", features = ["asm"]}
ark-poly = "0.3.0"

